### ISSUE TITLE
Warning -> Info in gradle task output

### ISSUE THREAD

**Issue by kvenn** [anthonycr/Mezzanine#30]
# Summary
**Type:** Feature Enhancement
The gradle task output currently shows as a warning but isn't any indication of something that _could_ be wrong. Therefore it might be better suited as an "info".

<img width="214" alt="screen shot 2018-04-02 at 4 00 59 pm" src="https://user-images.githubusercontent.com/1782467/38213420-14d0389c-368f-11e8-9fed-70e3251bb309.png">

**Comment by anthonycr** [comment]
This is caused by a change to the Kotlin compiler: https://github.com/JetBrains/kotlin/pull/1524

All `NOTE` type messages are now being outputted as warnings. Unfortunately, using `println()` to print log messages instead does not work like it does in Java projects, so I can't switch to that for logging.

The temporary solution is to remove logging altogether until either I find an appropriate way to log at the info level or until a change is made to the Kotlin compiler.

**Comment by anthonycr** [comment]
This is temporarily fixed in release 1.1.1. I am leaving the issue open though as a reminder to myself to revisit once there is some resolution to the issue in the Kotlin compiler.

**Comment by anthonycr** [comment]
Fixed in new KSP version.

**Comment by kvenn** [comment]
Great, thanks!
